import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillMail, AiFillFacebook, AiFillGithub } from 'react-icons/ai';

import { useState } from 'react';

import Image from 'next/image';

import deved from '../public/dev-ed-wave.png';

import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
    const [darkMode, setDarkMode] = useState(true);
    return (
        <div className={darkMode ? 'dark' : ''}>
            <Head>
                <title>Anas Alfaihan Portofolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between dark:text-white">
                        <h1 className="text-xl font-burtons">
                            Developed By Anas
                        </h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="cursor-pointer text-xl"
                                />
                            </li>
                            <li>
                                <a
                                    href="https://drive.google.com/file/d/1PHZYKk9o_YQNrDtaoHsEtLYimpGl3zwM/view?usp=sharing"
                                    className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                    target="_blank"
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">
                            Anas Alfaihan
                        </h2>
                        <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                            Full Stack Developer
                        </h3>
                        <p className="text-md py-5 leading-8 dark:text-gray-200 text-gray-800 md:text-xl max-w-lg mx-auto">
                            <span className="mb-2 block">
                                a full stack web developer with a passion for
                                building innovative and user-friendly web
                                applications.{' '}
                            </span>
                            With experience in front-end technologies like
                            <span className="font-bold"> React</span>, as well
                            as back-end languages like{' '}
                            <span className="font-bold">
                                {' '}
                                Python with Django
                            </span>
                            ,
                            <span className="font-bold">
                                JavaScript with nodejs
                            </span>
                            , I bring a well-rounded skill set to any project.
                        </p>
                    </div>
                    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                        <a href="mailto:Anas-Alfaihan@protonmail.com">
                            {' '}
                            <AiFillMail />{' '}
                        </a>
                        <a href="https://www.facebook.com/anas.abohamza.182">
                            {' '}
                            <AiFillFacebook />{' '}
                        </a>
                        <a href="https://github.com/Anas-Alfaihan">
                            {' '}
                            <AiFillGithub />{' '}
                        </a>
                    </div>
                    <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
                        <Image
                            alt={'a photo'}
                            src={deved}
                            layout="fill"
                            objectFit="cover"
                        />
                    </div>
                </section>

                <section className="py-10">
                    <div>
                        <h3 className="text-3xl py1 dark:text-white">
                            Portfolio
                        </h3>
                        <span className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Whether you need a custom website or a full-scale
                            web application, I'm dedicated to delivering{' '}
                            <span className="text-teal-500">high-quality</span>{' '}
                            code that meets your needs and exceeds your{' '}
                            <span className="text-teal-500">expectations</span>
                            .Take a look at some of my recent projects below,
                            and feel free to reach out if you have any questions
                            or would like to discuss your project further. Let's
                            build something amazing together!
                        </span>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web1}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web2}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web3}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web4}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web5}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                alt={'a photo'}
                                src={web6}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                            />
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
